# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.integration_api import IntegrationApi


class TestIntegrationApi(unittest.TestCase):
    """IntegrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntegrationApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_integrations_get(self) -> None:
        """Test case for project_project_id_integrations_get

        get all integrations
        """
        pass

    def test_project_project_id_integrations_integration_id_delete(self) -> None:
        """Test case for project_project_id_integrations_integration_id_delete

        Remove integration
        """
        pass

    def test_project_project_id_integrations_integration_id_get(self) -> None:
        """Test case for project_project_id_integrations_integration_id_get

        Get Integration
        """
        pass

    def test_project_project_id_integrations_integration_id_matchers_get(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_get

        Get Integration Matcher linked to integration extractor
        """
        pass

    def test_project_project_id_integrations_integration_id_matchers_matcher_id_delete(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_matcher_id_delete

        Removes integration matcher
        """
        pass

    def test_project_project_id_integrations_integration_id_matchers_matcher_id_put(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_matcher_id_put

        Updates Integration Matcher
        """
        pass

    def test_project_project_id_integrations_integration_id_matchers_post(self) -> None:
        """Test case for project_project_id_integrations_integration_id_matchers_post

        Add Integration Matcher
        """
        pass

    def test_project_project_id_integrations_integration_id_put(self) -> None:
        """Test case for project_project_id_integrations_integration_id_put

        Update Integration
        """
        pass

    def test_project_project_id_integrations_integration_id_values_extractvalue_id_delete(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_extractvalue_id_delete

        Removes integration extract value
        """
        pass

    def test_project_project_id_integrations_integration_id_values_extractvalue_id_put(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_extractvalue_id_put

        Updates Integration ExtractValue
        """
        pass

    def test_project_project_id_integrations_integration_id_values_get(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_get

        Get Integration Extracted Values linked to integration extractor
        """
        pass

    def test_project_project_id_integrations_integration_id_values_post(self) -> None:
        """Test case for project_project_id_integrations_integration_id_values_post

        Add Integration Extracted Value
        """
        pass

    def test_project_project_id_integrations_post(self) -> None:
        """Test case for project_project_id_integrations_post

        create a new integration
        """
        pass


if __name__ == '__main__':
    unittest.main()
