# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.key_store_api import KeyStoreApi


class TestKeyStoreApi(unittest.TestCase):
    """KeyStoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeyStoreApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_keys_get(self) -> None:
        """Test case for project_project_id_keys_get

        Get access keys linked to project
        """
        pass

    def test_project_project_id_keys_key_id_delete(self) -> None:
        """Test case for project_project_id_keys_key_id_delete

        Removes access key
        """
        pass

    def test_project_project_id_keys_key_id_put(self) -> None:
        """Test case for project_project_id_keys_key_id_put

        Updates access key
        """
        pass

    def test_project_project_id_keys_post(self) -> None:
        """Test case for project_project_id_keys_post

        Add access key
        """
        pass


if __name__ == '__main__':
    unittest.main()
