# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_client.models.project_backup import ProjectBackup

class TestProjectBackup(unittest.TestCase):
    """ProjectBackup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectBackup:
        """Test ProjectBackup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectBackup`
        """
        model = ProjectBackup()
        if include_optional:
            return ProjectBackup(
                meta = semaphore_client.models.project_backup_meta.ProjectBackup_meta(
                    name = '', 
                    alert = True, 
                    alert_chat = '', 
                    max_parallel_tasks = 0, 
                    type = '', ),
                templates = [
                    semaphore_client.models.project_backup_templates_inner.ProjectBackup_templates_inner(
                        inventory = '', 
                        repository = '', 
                        environment = '', 
                        view = '', 
                        name = '', 
                        playbook = '', 
                        arguments = '', 
                        description = '', 
                        allow_override_args_in_task = True, 
                        suppress_success_alerts = True, 
                        cron = '', 
                        build_template = '', 
                        autorun = True, 
                        survey_vars = '', 
                        start_version = '', 
                        type = '', 
                        vault_key = '', 
                        allow_override_branch_in_task = True, )
                    ],
                repositories = [
                    semaphore_client.models.project_backup_repositories_inner.ProjectBackup_repositories_inner(
                        name = '', 
                        git_url = '', 
                        git_branch = '', 
                        ssh_key = '', )
                    ],
                keys = [
                    semaphore_client.models.project_backup_keys_inner.ProjectBackup_keys_inner(
                        name = '', 
                        type = 'ssh', )
                    ],
                views = [
                    semaphore_client.models.project_backup_views_inner.ProjectBackup_views_inner(
                        name = '', 
                        position = 0, )
                    ],
                inventories = [
                    semaphore_client.models.project_backup_inventories_inner.ProjectBackup_inventories_inner(
                        name = '', 
                        inventory = '', 
                        ssh_key = '', 
                        become_key = '', 
                        type = 'static', )
                    ],
                environments = [
                    semaphore_client.models.project_backup_environments_inner.ProjectBackup_environments_inner(
                        name = '', 
                        password = '', 
                        json = '', 
                        env = '', )
                    ]
            )
        else:
            return ProjectBackup(
        )
        """

    def testProjectBackup(self):
        """Test ProjectBackup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
