# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_client.models.project_invite import ProjectInvite

class TestProjectInvite(unittest.TestCase):
    """ProjectInvite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectInvite:
        """Test ProjectInvite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectInvite`
        """
        model = ProjectInvite()
        if include_optional:
            return ProjectInvite(
                id = 1,
                project_id = 1,
                user_id = 1,
                email = '',
                role = 'manager',
                status = 'pending',
                inviter_user_id = 1,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                accepted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                inviter_user = semaphore_client.models.user.User(
                    id = 1, 
                    name = '', 
                    username = '', 
                    email = '', 
                    created = '', 
                    alert = True, 
                    admin = True, 
                    external = True, ),
                user = semaphore_client.models.user.User(
                    id = 1, 
                    name = '', 
                    username = '', 
                    email = '', 
                    created = '', 
                    alert = True, 
                    admin = True, 
                    external = True, )
            )
        else:
            return ProjectInvite(
        )
        """

    def testProjectInvite(self):
        """Test ProjectInvite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
