# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.template_api import TemplateApi


class TestTemplateApi(unittest.TestCase):
    """TemplateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplateApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_templates_get(self) -> None:
        """Test case for project_project_id_templates_get

        Get template
        """
        pass

    def test_project_project_id_templates_post(self) -> None:
        """Test case for project_project_id_templates_post

        create template
        """
        pass

    def test_project_project_id_templates_template_id_delete(self) -> None:
        """Test case for project_project_id_templates_template_id_delete

        Removes template
        """
        pass

    def test_project_project_id_templates_template_id_get(self) -> None:
        """Test case for project_project_id_templates_template_id_get

        Get template
        """
        pass

    def test_project_project_id_templates_template_id_put(self) -> None:
        """Test case for project_project_id_templates_template_id_put

        Updates template
        """
        pass

    def test_project_project_id_templates_template_id_stop_all_tasks_post(self) -> None:
        """Test case for project_project_id_templates_template_id_stop_all_tasks_post

        Stop all active tasks of template
        """
        pass


if __name__ == '__main__':
    unittest.main()
