# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.inventory_api import InventoryApi


class TestInventoryApi(unittest.TestCase):
    """InventoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InventoryApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_inventory_get(self) -> None:
        """Test case for project_project_id_inventory_get

        Get inventory
        """
        pass

    def test_project_project_id_inventory_inventory_id_delete(self) -> None:
        """Test case for project_project_id_inventory_inventory_id_delete

        Removes inventory
        """
        pass

    def test_project_project_id_inventory_inventory_id_get(self) -> None:
        """Test case for project_project_id_inventory_inventory_id_get

        Get inventory
        """
        pass

    def test_project_project_id_inventory_inventory_id_put(self) -> None:
        """Test case for project_project_id_inventory_inventory_id_put

        Updates inventory
        """
        pass

    def test_project_project_id_inventory_post(self) -> None:
        """Test case for project_project_id_inventory_post

        create inventory
        """
        pass


if __name__ == '__main__':
    unittest.main()
