# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_client.models.access_key_request_login_password import AccessKeyRequestLoginPassword

class TestAccessKeyRequestLoginPassword(unittest.TestCase):
    """AccessKeyRequestLoginPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessKeyRequestLoginPassword:
        """Test AccessKeyRequestLoginPassword
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessKeyRequestLoginPassword`
        """
        model = AccessKeyRequestLoginPassword()
        if include_optional:
            return AccessKeyRequestLoginPassword(
                password = 'password',
                login = 'username'
            )
        else:
            return AccessKeyRequestLoginPassword(
        )
        """

    def testAccessKeyRequestLoginPassword(self):
        """Test AccessKeyRequestLoginPassword"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
