# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.variable_group_api import VariableGroupApi


class TestVariableGroupApi(unittest.TestCase):
    """VariableGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VariableGroupApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_environment_environment_id_delete(self) -> None:
        """Test case for project_project_id_environment_environment_id_delete

        Removes environment
        """
        pass

    def test_project_project_id_environment_environment_id_get(self) -> None:
        """Test case for project_project_id_environment_environment_id_get

        Get environment
        """
        pass

    def test_project_project_id_environment_environment_id_put(self) -> None:
        """Test case for project_project_id_environment_environment_id_put

        Update environment
        """
        pass

    def test_project_project_id_environment_get(self) -> None:
        """Test case for project_project_id_environment_get

        Get environment
        """
        pass

    def test_project_project_id_environment_post(self) -> None:
        """Test case for project_project_id_environment_post

        Add environment
        """
        pass


if __name__ == '__main__':
    unittest.main()
