# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.repository_api import RepositoryApi


class TestRepositoryApi(unittest.TestCase):
    """RepositoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RepositoryApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_repositories_get(self) -> None:
        """Test case for project_project_id_repositories_get

        Get repositories
        """
        pass

    def test_project_project_id_repositories_post(self) -> None:
        """Test case for project_project_id_repositories_post

        Add repository
        """
        pass

    def test_project_project_id_repositories_repository_id_delete(self) -> None:
        """Test case for project_project_id_repositories_repository_id_delete

        Removes repository
        """
        pass

    def test_project_project_id_repositories_repository_id_get(self) -> None:
        """Test case for project_project_id_repositories_repository_id_get

        Get repository
        """
        pass

    def test_project_project_id_repositories_repository_id_put(self) -> None:
        """Test case for project_project_id_repositories_repository_id_put

        Updates repository
        """
        pass


if __name__ == '__main__':
    unittest.main()
