# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore.task_api import TaskApi


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskApi()

    def tearDown(self) -> None:
        pass

    def test_project_project_id_tasks_get(self) -> None:
        """Test case for project_project_id_tasks_get

        Get Tasks related to current project
        """
        pass

    def test_project_project_id_tasks_last_get(self) -> None:
        """Test case for project_project_id_tasks_last_get

        Get last 200 Tasks related to current project
        """
        pass

    def test_project_project_id_tasks_post(self) -> None:
        """Test case for project_project_id_tasks_post

        Starts a job
        """
        pass

    def test_project_project_id_tasks_task_id_delete(self) -> None:
        """Test case for project_project_id_tasks_task_id_delete

        Deletes task (including output)
        """
        pass

    def test_project_project_id_tasks_task_id_get(self) -> None:
        """Test case for project_project_id_tasks_task_id_get

        Get a single task
        """
        pass

    def test_project_project_id_tasks_task_id_output_get(self) -> None:
        """Test case for project_project_id_tasks_task_id_output_get

        Get task output
        """
        pass

    def test_project_project_id_tasks_task_id_raw_output_get(self) -> None:
        """Test case for project_project_id_tasks_task_id_raw_output_get

        Get task raw output
        """
        pass

    def test_project_project_id_tasks_task_id_stop_post(self) -> None:
        """Test case for project_project_id_tasks_task_id_stop_post

        Stop a job
        """
        pass


if __name__ == '__main__':
    unittest.main()
