# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from semaphore_client.models.terraform_task_params import TerraformTaskParams

class TestTerraformTaskParams(unittest.TestCase):
    """TerraformTaskParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerraformTaskParams:
        """Test TerraformTaskParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerraformTaskParams`
        """
        model = TerraformTaskParams()
        if include_optional:
            return TerraformTaskParams(
                plan = True,
                destroy = True,
                auto_approve = True,
                upgrade = True
            )
        else:
            return TerraformTaskParams(
        )
        """

    def testTerraformTaskParams(self):
        """Test TerraformTaskParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
