# coding: utf-8

# flake8: noqa

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "DefaultApi",
    "IntegrationApi",
    "InventoryApi",
    "KeyStoreApi",
    "ProjectApi",
    "RepositoryApi",
    "ScheduleApi",
    "TaskApi",
    "TemplateApi",
    "UserApi",
    "VariableGroupApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIToken",
    "AcceptInviteRequest",
    "AccessKey",
    "AccessKeyRequest",
    "AccessKeyRequestLoginPassword",
    "AccessKeyRequestSsh",
    "AnsibleTaskParams",
    "Environment",
    "EnvironmentRequest",
    "EnvironmentSecret",
    "EnvironmentSecretRequest",
    "Event",
    "InfoType",
    "Integration",
    "IntegrationExtractValue",
    "IntegrationExtractValueRequest",
    "IntegrationMatcher",
    "IntegrationMatcherRequest",
    "IntegrationRequest",
    "Inventory",
    "InventoryRequest",
    "Login",
    "LoginMetadata",
    "LoginMetadataOidcProvidersInner",
    "Project",
    "ProjectBackup",
    "ProjectBackupEnvironmentsInner",
    "ProjectBackupInventoriesInner",
    "ProjectBackupKeysInner",
    "ProjectBackupMeta",
    "ProjectBackupRepositoriesInner",
    "ProjectBackupTemplatesInner",
    "ProjectBackupViewsInner",
    "ProjectInvite",
    "ProjectInviteRequest",
    "ProjectProjectIdPutRequest",
    "ProjectProjectIdRoleGet200Response",
    "ProjectProjectIdTasksPostRequest",
    "ProjectProjectIdUsersPostRequest",
    "ProjectProjectIdUsersUserIdPutRequest",
    "ProjectRequest",
    "ProjectUser",
    "Repository",
    "RepositoryRequest",
    "Runner",
    "Schedule",
    "ScheduleRequest",
    "Task",
    "TaskOutput",
    "TaskParams",
    "TaskPrams",
    "Template",
    "TemplateRequest",
    "TemplateSurveyVar",
    "TemplateSurveyVarValue",
    "TemplateVault",
    "TerraformTaskParams",
    "User",
    "UserPutRequest",
    "UserRequest",
    "UsersUserIdPasswordPostRequest",
    "View",
    "ViewRequest",
]

# import apis into sdk package
from semaphore.authentication_api import AuthenticationApi as AuthenticationApi
from semaphore.default_api import DefaultApi as DefaultApi
from semaphore.integration_api import IntegrationApi as IntegrationApi
from semaphore.inventory_api import InventoryApi as InventoryApi
from semaphore.key_store_api import KeyStoreApi as KeyStoreApi
from semaphore.project_api import ProjectApi as ProjectApi
from semaphore.repository_api import RepositoryApi as RepositoryApi
from semaphore.schedule_api import ScheduleApi as ScheduleApi
from semaphore.task_api import TaskApi as TaskApi
from semaphore.template_api import TemplateApi as TemplateApi
from semaphore.user_api import UserApi as UserApi
from semaphore.variable_group_api import VariableGroupApi as VariableGroupApi

# import ApiClient
from semaphore_client.api_response import ApiResponse as ApiResponse
from semaphore_client.api_client import ApiClient as ApiClient
from semaphore_client.configuration import Configuration as Configuration
from semaphore_client.exceptions import OpenApiException as OpenApiException
from semaphore_client.exceptions import ApiTypeError as ApiTypeError
from semaphore_client.exceptions import ApiValueError as ApiValueError
from semaphore_client.exceptions import ApiKeyError as ApiKeyError
from semaphore_client.exceptions import ApiAttributeError as ApiAttributeError
from semaphore_client.exceptions import ApiException as ApiException

# import models into sdk package
from semaphore_client.models.api_token import APIToken as APIToken
from semaphore_client.models.accept_invite_request import AcceptInviteRequest as AcceptInviteRequest
from semaphore_client.models.access_key import AccessKey as AccessKey
from semaphore_client.models.access_key_request import AccessKeyRequest as AccessKeyRequest
from semaphore_client.models.access_key_request_login_password import AccessKeyRequestLoginPassword as AccessKeyRequestLoginPassword
from semaphore_client.models.access_key_request_ssh import AccessKeyRequestSsh as AccessKeyRequestSsh
from semaphore_client.models.ansible_task_params import AnsibleTaskParams as AnsibleTaskParams
from semaphore_client.models.environment import Environment as Environment
from semaphore_client.models.environment_request import EnvironmentRequest as EnvironmentRequest
from semaphore_client.models.environment_secret import EnvironmentSecret as EnvironmentSecret
from semaphore_client.models.environment_secret_request import EnvironmentSecretRequest as EnvironmentSecretRequest
from semaphore_client.models.event import Event as Event
from semaphore_client.models.info_type import InfoType as InfoType
from semaphore_client.models.integration import Integration as Integration
from semaphore_client.models.integration_extract_value import IntegrationExtractValue as IntegrationExtractValue
from semaphore_client.models.integration_extract_value_request import IntegrationExtractValueRequest as IntegrationExtractValueRequest
from semaphore_client.models.integration_matcher import IntegrationMatcher as IntegrationMatcher
from semaphore_client.models.integration_matcher_request import IntegrationMatcherRequest as IntegrationMatcherRequest
from semaphore_client.models.integration_request import IntegrationRequest as IntegrationRequest
from semaphore_client.models.inventory import Inventory as Inventory
from semaphore_client.models.inventory_request import InventoryRequest as InventoryRequest
from semaphore_client.models.login import Login as Login
from semaphore_client.models.login_metadata import LoginMetadata as LoginMetadata
from semaphore_client.models.login_metadata_oidc_providers_inner import LoginMetadataOidcProvidersInner as LoginMetadataOidcProvidersInner
from semaphore_client.models.project import Project as Project
from semaphore_client.models.project_backup import ProjectBackup as ProjectBackup
from semaphore_client.models.project_backup_environments_inner import ProjectBackupEnvironmentsInner as ProjectBackupEnvironmentsInner
from semaphore_client.models.project_backup_inventories_inner import ProjectBackupInventoriesInner as ProjectBackupInventoriesInner
from semaphore_client.models.project_backup_keys_inner import ProjectBackupKeysInner as ProjectBackupKeysInner
from semaphore_client.models.project_backup_meta import ProjectBackupMeta as ProjectBackupMeta
from semaphore_client.models.project_backup_repositories_inner import ProjectBackupRepositoriesInner as ProjectBackupRepositoriesInner
from semaphore_client.models.project_backup_templates_inner import ProjectBackupTemplatesInner as ProjectBackupTemplatesInner
from semaphore_client.models.project_backup_views_inner import ProjectBackupViewsInner as ProjectBackupViewsInner
from semaphore_client.models.project_invite import ProjectInvite as ProjectInvite
from semaphore_client.models.project_invite_request import ProjectInviteRequest as ProjectInviteRequest
from semaphore_client.models.project_project_id_put_request import ProjectProjectIdPutRequest as ProjectProjectIdPutRequest
from semaphore_client.models.project_project_id_role_get200_response import ProjectProjectIdRoleGet200Response as ProjectProjectIdRoleGet200Response
from semaphore_client.models.project_project_id_tasks_post_request import ProjectProjectIdTasksPostRequest as ProjectProjectIdTasksPostRequest
from semaphore_client.models.project_project_id_users_post_request import ProjectProjectIdUsersPostRequest as ProjectProjectIdUsersPostRequest
from semaphore_client.models.project_project_id_users_user_id_put_request import ProjectProjectIdUsersUserIdPutRequest as ProjectProjectIdUsersUserIdPutRequest
from semaphore_client.models.project_request import ProjectRequest as ProjectRequest
from semaphore_client.models.project_user import ProjectUser as ProjectUser
from semaphore_client.models.repository import Repository as Repository
from semaphore_client.models.repository_request import RepositoryRequest as RepositoryRequest
from semaphore_client.models.runner import Runner as Runner
from semaphore_client.models.schedule import Schedule as Schedule
from semaphore_client.models.schedule_request import ScheduleRequest as ScheduleRequest
from semaphore_client.models.task import Task as Task
from semaphore_client.models.task_output import TaskOutput as TaskOutput
from semaphore_client.models.task_params import TaskParams as TaskParams
from semaphore_client.models.task_prams import TaskPrams as TaskPrams
from semaphore_client.models.template import Template as Template
from semaphore_client.models.template_request import TemplateRequest as TemplateRequest
from semaphore_client.models.template_survey_var import TemplateSurveyVar as TemplateSurveyVar
from semaphore_client.models.template_survey_var_value import TemplateSurveyVarValue as TemplateSurveyVarValue
from semaphore_client.models.template_vault import TemplateVault as TemplateVault
from semaphore_client.models.terraform_task_params import TerraformTaskParams as TerraformTaskParams
from semaphore_client.models.user import User as User
from semaphore_client.models.user_put_request import UserPutRequest as UserPutRequest
from semaphore_client.models.user_request import UserRequest as UserRequest
from semaphore_client.models.users_user_id_password_post_request import UsersUserIdPasswordPostRequest as UsersUserIdPasswordPostRequest
from semaphore_client.models.view import View as View
from semaphore_client.models.view_request import ViewRequest as ViewRequest

