# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InfoType(BaseModel):
    """
    InfoType
    """ # noqa: E501
    version: Optional[StrictStr] = None
    ansible: Optional[StrictStr] = None
    web_host: Optional[StrictStr] = None
    use_remote_runner: Optional[StrictBool] = None
    auth_methods: Optional[Dict[str, Any]] = None
    git_client: Optional[StrictStr] = None
    schedule_timezone: Optional[StrictStr] = None
    premium_features: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["version", "ansible", "web_host", "use_remote_runner", "auth_methods", "git_client", "schedule_timezone", "premium_features"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InfoType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InfoType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "ansible": obj.get("ansible"),
            "web_host": obj.get("web_host"),
            "use_remote_runner": obj.get("use_remote_runner"),
            "auth_methods": obj.get("auth_methods"),
            "git_client": obj.get("git_client"),
            "schedule_timezone": obj.get("schedule_timezone"),
            "premium_features": obj.get("premium_features")
        })
        return _obj


