# coding: utf-8

"""
    Semaphore API

    Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

    The version of the OpenAPI document: 2.16.14
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from semaphore_client.models.user import User
from typing import Optional, Set
from typing_extensions import Self

class ProjectInvite(BaseModel):
    """
    ProjectInvite
    """ # noqa: E501
    id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    project_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    user_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="User ID for user-based invites (optional)")
    email: Optional[StrictStr] = Field(default=None, description="Email address for email-based invites (optional)")
    role: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    inviter_user_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="ID of the user who created the invite")
    created: Optional[datetime] = Field(default=None, description="When the invite was created")
    expires_at: Optional[datetime] = Field(default=None, description="When the invite expires (optional)")
    accepted_at: Optional[datetime] = Field(default=None, description="When the invite was accepted (optional)")
    inviter_user: Optional[User] = None
    user: Optional[User] = None
    __properties: ClassVar[List[str]] = ["id", "project_id", "user_id", "email", "role", "status", "inviter_user_id", "created", "expires_at", "accepted_at", "inviter_user", "user"]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['owner', 'manager', 'task_runner', 'guest']):
            raise ValueError("must be one of enum values ('owner', 'manager', 'task_runner', 'guest')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'accepted', 'declined', 'expired']):
            raise ValueError("must be one of enum values ('pending', 'accepted', 'declined', 'expired')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectInvite from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of inviter_user
        if self.inviter_user:
            _dict['inviter_user'] = self.inviter_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectInvite from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project_id": obj.get("project_id"),
            "user_id": obj.get("user_id"),
            "email": obj.get("email"),
            "role": obj.get("role"),
            "status": obj.get("status"),
            "inviter_user_id": obj.get("inviter_user_id"),
            "created": obj.get("created"),
            "expires_at": obj.get("expires_at"),
            "accepted_at": obj.get("accepted_at"),
            "inviter_user": User.from_dict(obj["inviter_user"]) if obj.get("inviter_user") is not None else None,
            "user": User.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


